########################
## Cloud Build Config ##
########################

isEnabled: true
docker:
  preset: "yarn"
  preparationCommand: ""
  imageFrom: ""
  ignore: "node_modules"
build:
  command: "npm i"
  outputFolder: ""
run:
  command: "npm start"
  envs:
    - name: APP_ENV
      value: 'sm://{{.projectId}}/env'
addOns:
  isWebsite: false
  firestore: false
  inSecure: true
