########################
## Cloud Build Config ##
########################

isEnabled: true
docker:
  preset: "yarn"
  ignore: "node_modules"
build:
  command: "npm i --production"
  outputFolder: ""
run:
  command: "npm start"
  envs:
    - name: APP_ENV
      value: 'sm://{{.projectId}}/env'
settings:
  isWebsite: false
  inSecure: true
